### ISSUE TITLE
Mux condition width change

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/firrtl-interpreter#15]
As a result of ucb-bar/firrtl@a6c8493, a Mux condition is no longer constrained to be one bit. As a result, the Mux case in LoFirrtlExpressionEvaluator.scala encounters a:

```
throw InterpreterException(s"mux($condition) must be (0|1).U<1> was $v $sourceInfo")
```

This shows up in the tutorials for the VecSearch and Tbl examples.

Is this a firrtl bug or an invalid firrtl-interpreter constraint?

**Comment by ccelio** [comment]
This looks related to https://github.com/ucb-bar/firrtl/issues/206?
