### ISSUE TITLE
Request ability to poke not just the interface but also the internal state registers

### ISSUE THREAD

**Issue by stevenmburns** [ucb-bar/firrtl-interpreter#22]
In InterpretiveTester.scala, you mentioned that you might support this later.
We are interested because then we can write tests where we first set the state, then write a sequence of pokes and steps, observing the outputs. It some cases, this is better than a long sequence of pokes (on only the interface) to establish a particular stare.

`class InterpretiveTester(input: String, vcdOutputFileName: String = "") {
  var expectationsMet = 0

  val interpreter = FirrtlTerp(input)
  if(vcdOutputFileName.nonEmpty) {
    interpreter.makeVCDLogger(vcdOutputFileName)
  }
  def writeVCD(): Unit = {
    interpreter.writeVCD()
  }

  def setVerbose(value: Boolean = true): Unit = {
    interpreter.setVerbose(value)
  }

  val startTime = System.nanoTime()

  /**
    * Pokes value to the port referenced by string
    * Warning: pokes to components other than input ports is currently
    * not supported but does not cause an error warning
    * This feature should be supported soon
    *
    * @param name the name of a port
    * @param value a value to put on that port
    */
  def poke(name: String, value: BigInt): Unit = {
    try {
      interpreter.setValueWithBigInt(name, value)
    }
    catch {
      case ie: InterpreterException =>
        println(s"Error: poke($name, $value)")
        throw ie
    }
  }
`

**Comment by chick** [comment]
This doesn't sound too hard, I'll take a look at it.  Do you know of any edge cases or ambiguity's that this might create.

**Comment by chick** [comment]
@stevenmburns I have pushed a new branch poke-registers that implements poking of registers (no other things currently).  The InterpretiveTesterSpec has a test added at line 43 that demonstrates the feature.  Are you able to test this?

**Comment by stevenmburns** [comment]
Sorry for the delay. I missed this update. I was able to test this and it does do what I want.
I also made these changes in "chisel-testers" so I could poke these signals by name (path expressed as a String.)
Maybe there is a better interface possible. (I dropped the "force" argument always setting it to true.)

`diff --git a/src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala b/src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
index 4222dac..5d8ad39 100644
--- a/src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
+++ b/src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
@@ -58,19 +58,23 @@ private[iotesters] class FirrtlTerpBackend(dut: Module,
 
   def poke(path: String, value: BigInt)
           (implicit logger: PrintStream, verbose: Boolean, base: Int): Unit = {
-    assert(false)
+     interpretiveTester.poke( path, value, true)         
+     if (verbose) logger println s"  POKE $path <- ${bigIntToStr(value, base)}"
   }
 
   def peek(path: String)
           (implicit logger: PrintStream, verbose: Boolean, base: Int): BigInt = {
-    assert(false)
-    BigInt(rnd.nextInt)
+    val result = interpretiveTester.peek( path)
+    if (verbose) logger println s"  PEEK $path -> ${bigIntToStr(result, base)}"
+    result 
   }
 
   def expect(path: String, expected: BigInt, msg: => String)
             (implicit logger: PrintStream, verbose: Boolean, base: Int) : Boolean = {
-    assert(false)
-    false
+    val got = interpretiveTester.peek(path)
+    val good = got == expected
+    if (verbose) logger println s"""$msg  EXPECT $path -> ${bigIntToStr(got, base)} == ${bigIntToStr(expected, base)} ${if (good) "PASS" else "FAIL"}"""
+    good
   }
 
   def step(n: Int)(implicit logger: PrintStream): Unit = {
`

**Comment by stevenmburns** [comment]
Closing because it does what I want.
