### ISSUE TITLE
Runtime assert (or stop) should raise an exception

### ISSUE THREAD

**Issue by stevenmburns** [ucb-bar/firrtl-interpreter#30]
We see different behavior in the interpretiveTester and the HWSteppedIOTester when runtime assertions fail. The interpretiveTester doesn't stop (in fact the test passes), while the verilator-based testers stop (and the test fails.)

I think we want the test to fail or better yet an exception be raised that I can catch in the test if necessary.

The code below exposes the difference. Both tests should fail.

```
package myRisc

import chisel3._

class mockRegFileOut() extends Module{
  val io = new Bundle {
    val addr = Bits(INPUT, 8)
    val DataO = Bits(OUTPUT, 32)
  }

//  assert(io.addr === UInt(0),"ASSERT:Read at the wrong Register")

  when(io.addr === UInt(0)){
    io.DataO := UInt(128)
  }.otherwise{
    printf("STOP:Read at the wrong Register\n")
    chisel3.core.stop(47)
  }
}

class myRisc extends Module{
  val io = new Bundle {
    val wrData = Bits(INPUT, 32)

    val valid  = Bool(OUTPUT)
    val out    = Bits(OUTPUT, 32)
  }

  val inst = io.wrData


  //instantiate mock
  val mock = Module(new mockRegFileOut).io
  mock.addr := UInt(16)//inst(15, 8)
// Comment the next line to see a mocking failure
//  mock.addr := inst(15, 8)


  val rci  = inst(23,16) 

  when (rci === UInt(255)){
    io.valid := Bool(true)
    io.out := mock.DataO
  }.otherwise{
    io.valid := Bool(false)
  }

}

import chisel3.iotesters._
import firrtl_interpreter.InterpretiveTester

class myRiscInterpretiveTest extends ChiselFlatSpec {
  val s = chisel3.Driver.emit( () => new myRisc)

  val tester = new InterpretiveTester(s)

  s"myRisc" should s"work" in {
    tester.poke( "io_wrData", (0<<24)+(255<<16))
    tester.step(1)
//    tester.expect( "io_valid", 1)
//    tester.expect( "io_out", 128)
  }  
  tester.report()
}

class MyRiscTester extends SteppedHWIOTester
{
  val device_under_test = Module( new myRisc)
  val c = device_under_test

  poke( c.io.wrData, (0<<24)+(255<<16))
  step(1)
//  expect( c.io.valid, 1)
//  expect( c.io.out, 128)
}

class myRiscTest extends ChiselFlatSpec {
  s"myRisc" should s"work" in {
    assertTesterPasses { new MyRiscTester }
 }
}
```

**Comment by chick** [comment]
@stevenmburns, I am making it looks something like the following.  There's a bit of complication caused in this fix, so it's taking a little longer to push
```
Circuit state created
evaluator created
STOP:Read at the wrong Register
Failure: @[RunTimeAssertSpec.scala 20:22] returned 47

Failure: Stop result 47
firrtl_interpreter.StopException: Failure: Stop result 47
	at firrtl_interpreter.InterpreterException$.apply(StopException.scala:10)
	at firrtl_interpreter.FirrtlTerp.evaluateCircuit(FirrtlTerp.scala:115)
	at firrtl_interpreter.FirrtlTerp$.apply(FirrtlTerp.scala:157)
```

**Comment by chick** [comment]
@stevenmburns I have made a new pull request #31 that I think addresses the issue.  It's a bigger commit than I would like. But it a lot came up as I made the necessary changes.  If you can test it it would be great.  The StopBehaviorSpec is a firrtl only version of example above.

**Comment by stevenmburns** [comment]
I'll get to it by Monday noon. Thanks for your improvements. It is helping
us out a lot.

On Sep 23, 2016 12:01 PM, "Chick Markley" <notifications@github.com> wrote:

@stevenmburns <https://github.com/stevenmburns> I have made a new pull
request #31 <https://github.com/ucb-bar/firrtl-interpreter/pull/31> that I
think addresses the issue. It's a bigger commit than I would like. But it a
lot came up as I made the necessary changes. If you can test it it would be
great. The StopBehaviorSpec is a firrtl only version of example above.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ucb-bar/firrtl-interpreter/issues/30#issuecomment-249261464>,
or mute the thread
