### ISSUE TITLE
Error happens when initializing registers

### ISSUE THREAD

**Issue by pingfanm** [ucb-bar/firrtl-interpreter#37]
When we run this code:

```
package myRegInitTest.test
import chisel3._
import chisel3.iotesters._
import firrtl_interpreter.InterpretiveTester
import org.scalatest.{ Matchers, FlatSpec, GivenWhenThen}
class mySubModule extends Module{
  val io = new Bundle{
    val In = UInt(INPUT, width = 8)
    val Out = UInt(OUTPUT, width = 8)
  }
  //val delayReg = Reg(UInt(width = 8))
  val delayReg = Reg( init = UInt(0,width = 8))
  delayReg := io.In
  io.Out := delayReg
}

class myModule extends Module{
  val io = new Bundle{
    val In = UInt(INPUT, width = 8)
    val Out = UInt(OUTPUT, width = 8)
  }
  val subModule = Module(new mySubModule).io 
  subModule.In := io.In
  io.Out := subModule.Out
}

class myModuleTest extends ChiselFlatSpec with Matchers{
  val s = chisel3.Driver.emit( () => new myModule)
  val tester = new InterpretiveTester(s)
  "myModule" should "output the data correctly" in {
    tester.poke( "io_In", 1)
    tester.step(1)
    tester.expect( "io_Out", 1)
  }
}
```

We see this error: 
[info]   java.lang.AssertionError: assertion failed: Cycle cannot be called when stale, refresh should occur at a higher level
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at firrtl_interpreter.CircuitState.cycle(CircuitState.scala:95)
[info]   at firrtl_interpreter.FirrtlTerp.cycle(FirrtlTerp.scala:149)
[info]   at firrtl_interpreter.InterpretiveTester$$anonfun$step$1.apply$mcVI$sp(InterpretiveTester.scala:140)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
[info]   at firrtl_interpreter.InterpretiveTester.step(InterpretiveTester.scala:139)
[info]   at myRegInitTest.test.myModuleTest$$anonfun$1.apply$mcV$sp(bug-reg-init-in-submodule.scala:44)
[info]   at myRegInitTest.test.myModuleTest$$anonfun$1.apply(bug-reg-init-in-submodule.scala:42)
[info]   at myRegInitTest.test.myModuleTest$$anonfun$1.apply(bug-reg-init-in-submodule.scala:42)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)

If we change `val delayReg = Reg( init = UInt(0,width = 8))` to `val delayReg = Reg(UInt(width = 8))`, the error disappears. It seems like when we initialize the register in the submodule, we will get this error.

**Comment by stevenmburns** [comment]
@chick Pingfan work for me. This seems to be a new error, when using top of trunk. Let us know if we need to use a specific contour of chisel3, firrtl, firrtl-interpreter, and chisel-testers.

**Comment by chick** [comment]
I will get this fixed as soon as I can hopefully by late tomorrow.

**Comment by chick** [comment]
I should have a fix tomorrow, I have fixed the interpreter with respect to the examples above, but the fix has causes a problem in one of the other tests, should have it tracked down soon

**Comment by chick** [comment]
@pingfanm : Try PR #38  if you have a chance, I think it will fix the problem. When using the InterpretiveTester directly as you have done in the examples above, you must explicitly initiate any reset sequences yourself.  The chisel-testers do this magically in the background.  I have added a little glyph  when showing uninitialized/poison values in the interpreter so they look like ☠99☠,.

**Comment by chick** [comment]
I believe this has been fixed
