### ISSUE TITLE
Bad Error Message when exceeding width

### ISSUE THREAD

**Issue by sagark** [ucb-bar/firrtl-interpreter#39]
I was getting errors like the following from the firrtl interpreter using the PeekPokeTester due to a size mismatch:

firrtl_interpreter.InterpreterException: error: ConcreteUInt(173525750563694249187527616882606750007724264234400840961006006951017764837122407600528949487992140992211789212913336790795370042985857600933089979226285111525816415353908842, 512) bad width 512 needs 31

However, the "31" here should have been 576. I believe this is coming from the `.toInt` here:
https://github.com/ucb-bar/firrtl-interpreter/blob/633b79d53fd48f4f3a9ba36453b7606f79382f73/src/main/scala/firrtl_interpreter/Concrete.scala#L337

I was able to get the correct error message by removing the .toInt.

I can reproduce this using a smaller example:
https://github.com/sagark/chisel-template

This produces:
Exception during evaluation: error: ConcreteUInt(773733740659399356, 40) bad width 40 needs 31
Expression Evaluation stack
   0 io_gcdio_z:Output -> stuff.io_z

**Comment by chick** [comment]
@sagark Yes, I think that toInt should go away.  But that will just fix the error message.  Does the 512 as the second argument there represent a bug as well, or is it just part of the illustration.  Let me know and I will fix.

**Comment by sagark** [comment]
@chick I believe the 512 was correct, In the original case I was connecting a 576 bit input to a 512 bit output. The error went away once I fixed this. Thanks!
