### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by grebe** [ucb-bar/firrtl-interpreter#55]
I tried building against firrtl ucb-bar/firrtl@c19a53a562883ebb7d9c6131c4ef308bcfbd720a (current head) and I got errors.

[error] /Users/rigge/src/firrtl-interpreter/src/main/scala/firrtl_interpreter/ToLoFirrtl.scala:15: type mismatch;
[error]  found   : firrtl.ir.Circuit
[error]  required: firrtl.CircuitState
[error]     val compileResult = compiler.compile(c, new AnnotationMap(Seq.empty), new StringWriter())
[error]                                          ^
[error] firrtl-interpreter/src/main/scala/firrtl_interpreter/ToLoFirrtl.scala:15: type mismatch;
[error]  found   : firrtl.Annotations.AnnotationMap
[error]  required: java.io.Writer
[error]     val compileResult = compiler.compile(c, new AnnotationMap(Seq.empty), new StringWriter())
[error]                                             ^
[error] two errors found
[error] firrtl-interpreter/src/main/scala/firrtl_interpreter/ToLoFirrtl.scala:15: type mismatch;
[error]  found   : firrtl.ir.Circuit
[error]  required: firrtl.CircuitState
[error]     val compileResult = compiler.compile(c, new AnnotationMap(Seq.empty), new StringWriter())
[error]                                          ^
[error] firrtl-interpreter/src/main/scala/firrtl_interpreter/ToLoFirrtl.scala:15: type mismatch;
[error]  found   : firrtl.Annotations.AnnotationMap
[error]  required: java.io.Writer
[error]     val compileResult = compiler.compile(c, new AnnotationMap(Seq.empty), new StringWriter())
[error]                                             ^

**Comment by grebe** [comment]
I just looked at #54- does that fix this?

**Comment by ucbjrl** [comment]
Fixed by #54
